name: calafi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  fl_chart: ^0.71.0
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.4
  flutter_svg: ^2.0.17
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/
    - assets/font/
    - assets/icon/
    - assets/icon/alram/
    - assets/icon/week/
    - assets/icon/my/
    - assets/icon/heart/
    - assets/icon/search/
    - assets/icon/detail/
    - assets/icon/footer/
    - assets/icon/footer/red/
    - assets/images/
    - assets/images/rank/

  fonts:
    - family: PretendardBold
      fonts:
        - asset: assets/font/Pretendard-Bold.otf
    - family: PretendardSemiBold
      fonts:
        - asset: assets/font/Pretendard-SemiBold.otf
    - family: PretendardRegular
      fonts:
        - asset: assets/font/Pretendard-Regular.otf
    - family: PretendardLight
      fonts:
        - asset: assets/font/Pretendard-Light.otf
    - family: PretendardMedium
      fonts:
        - asset: assets/font/Pretendard-Medium.otf